# Generated by Django 6.0.3 on 2026-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSDSEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_text', models.CharField(help_text='e.g. Oct 24 - 26, 2024', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
