# Generated by Django 6.0.3 on 2026-05-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(help_text='Short code, e.g. DU, JU, CU', max_length=20)),
                ('university_name', models.CharField(help_text='Full university name', max_length=255)),
                ('event_description', models.CharField(help_text='e.g. October 2023 • Genomic Sequencing Workshop', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campus_seminars/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Campus Seminar',
                'verbose_name_plural': 'Campus Seminars',
                'ordering': ['order', 'id'],
            },
        ),
    ]
