# Generated by Django 6.0.3 on 2026-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0002_campusseminar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Full URL, e.g. https://forms.google.com/...')),
            ],
            options={
                'verbose_name': 'Seminar Link',
                'verbose_name_plural': 'Seminar Links',
            },
        ),
    ]
