# Generated by Django 6.0.3 on 2026-05-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0003_seminarlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarProgramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_seminar_url', models.URLField(blank=True, help_text="'Request This Program' link for the On Campus Free Bioinformatics Seminar card.")),
                ('clinical_seminar_url', models.URLField(blank=True, help_text="'Request This Program' link for the On Campus Free Clinical Bioinformatics Seminar card.")),
                ('training_program_url', models.URLField(blank=True, help_text="'Request This Program' link for the On-Campus Bioinformatics Based Training Program card.")),
                ('quiz_url', models.URLField(blank=True, help_text="URL for the 'Take the Seminar Quiz' button shown between the program cards and intro section.")),
            ],
            options={
                'verbose_name': 'Seminar Program Config',
                'verbose_name_plural': 'Seminar Program Config',
            },
        ),
        migrations.DeleteModel(
            name='SeminarLink',
        ),
    ]
