# Generated by Django 6.0.3 on 2026-05-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0004_seminarprogramconfig_delete_seminarlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Award year, e.g. 2026')),
                ('name', models.CharField(max_length=255)),
                ('role_label', models.CharField(help_text='e.g. Best Bioinformatics Campus Coordinator 2025', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='campus_coordinators/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Campus Coordinator Honor',
                'verbose_name_plural': 'Campus Coordinator Honors',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='school', help_text="Material Symbol icon name, e.g. 'school', 'biotech'", max_length=100)),
                ('collab_type', models.CharField(choices=[('university', 'University'), ('club', 'Club / Student Org')], default='university', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
                'ordering': ['collab_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='competitions/')),
                ('apply_url', models.URLField(blank=True, help_text='Application / participation link')),
                ('is_active', models.BooleanField(default=True, help_text='Active contest or past winner?')),
                ('placement', models.CharField(blank=True, choices=[('', 'Active Contest'), ('1st', '1st Place'), ('2nd', '2nd Place'), ('3rd', '3rd Place')], default='', help_text='For past winners only', max_length=10)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year, for past winners', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'ordering': ['-is_active', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='research_talks/')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube or external video link')),
                ('duration', models.CharField(blank=True, help_text='e.g. 45:12', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Research Talk',
                'verbose_name_plural': 'Research Talks',
                'ordering': ['order', 'id'],
            },
        ),
    ]
