# Generated by Django 6.0.3 on 2026-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0005_campuscoordinator_collaboration_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtalk',
            name='agenda_url',
            field=models.URLField(blank=True, help_text='Link to view the agenda or details'),
        ),
        migrations.AddField(
            model_name='researchtalk',
            name='apply_url',
            field=models.URLField(blank=True, help_text='Link to apply or register for the talk'),
        ),
    ]
