# Generated by Django 6.0.3 on 2026-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0006_researchtalk_agenda_url_researchtalk_apply_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='collaborations/logos/'),
        ),
    ]
