# Generated by Django 6.0.3 on 2026-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0007_collaboration_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsored_programs/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sponsored Program',
                'verbose_name_plural': 'Sponsored Programs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
