# Generated by Django 6.0.3 on 2026-05-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0008_sponsoredprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarprogramconfig',
            name='quiz_image',
            field=models.ImageField(blank=True, help_text='Optional banner image for the Quiz section', null=True, upload_to='seminar_configs/'),
        ),
    ]
