# Generated by Django 6.0.3 on 2026-05-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0009_seminarprogramconfig_quiz_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title or caption for the memory', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coordinator_memories/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Coordinator Memory',
                'verbose_name_plural': 'Coordinator Memories',
                'ordering': ['order', 'id'],
            },
        ),
    ]
