# Generated by Django 6.0.3 on 2026-08-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0010_coordinatormemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusCoordinatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_url', models.URLField(blank=True, help_text="URL for the 'Apply Now' button on the Campus Coordinators page.")),
            ],
            options={
                'verbose_name': 'Campus Coordinator Config',
                'verbose_name_plural': 'Campus Coordinator Config',
            },
        ),
    ]
