# Generated by Django 6.0.3 on 2026-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0011_campuscoordinatorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='details_url',
            field=models.URLField(blank=True, help_text='Link to read details'),
        ),
    ]
