# Generated by Django 6.0.3 on 2026-08-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0012_competition_details_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsdsevent',
            name='details_url',
            field=models.URLField(blank=True, help_text='Details URL', null=True),
        ),
        migrations.AlterField(
            model_name='bsdsevent',
            name='url',
            field=models.URLField(blank=True, help_text='Apply Now URL', null=True),
        ),
    ]
