# Generated by Django 6.0.3 on 2026-08-29 17:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsds', '0013_bsdsevent_details_url_alter_bsdsevent_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsdsevent',
            name='details_url',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='details_url',
        ),
        migrations.AddField(
            model_name='bsdsevent',
            name='details',
            field=tinymce.models.HTMLField(blank=True, help_text='Event Details', null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='details',
            field=tinymce.models.HTMLField(blank=True, help_text='Competition Details', null=True),
        ),
    ]
