# Generated by Django 6.0.3 on 2026-03-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief biography', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='order_in_department',
            field=models.IntegerField(default=0, help_text='Sorting order within the department'),
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.IntegerField(default=0, help_text='Used to sort departments in the UI'),
        ),
    ]
