# Generated by Django 6.0.3 on 2026-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSDSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Bioinformatics Research Wings', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload an image for this BSDS item', null=True, upload_to='bsds/thumbnails/')),
                ('details_url', models.CharField(blank=True, help_text="Link for the 'Details' button. Can be a full URL or relative path.", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this item appears on the page')),
            ],
            options={
                'verbose_name': 'BSDS Item',
                'verbose_name_plural': 'BSDS Items',
                'ordering': ['order', 'title'],
            },
        ),
    ]
