# Generated by Django 6.0.3 on 2026-05-04 12:33

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('employment_type', models.CharField(help_text='e.g. Full-time, Part-time', max_length=100)),
                ('location', models.CharField(help_text='e.g. Dhaka, Chittagong', max_length=100)),
                ('vacancy', models.PositiveIntegerField(default=1)),
                ('posted_date', models.DateField()),
                ('deadline', models.DateField()),
                ('short_description', models.TextField(help_text='Shown in the list view')),
                ('job_overview', tinymce.models.HTMLField(blank=True, null=True)),
                ('required_profile', tinymce.models.HTMLField(blank=True, null=True)),
                ('role_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('salary_info', tinymce.models.HTMLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
                'ordering': ['-posted_date'],
            },
        ),
    ]
