# Generated by Django 6.0.3 on 2026-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='apply_url',
            field=models.URLField(blank=True, help_text='Link to external application form (e.g. Google Form). If empty, uses default mailto link.', null=True),
        ),
    ]
