# Generated by Django 6.0.3 on 2026-05-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bsdsevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BSDSEvent',
        ),
    ]
