# Generated by Django 6.0.3 on 2026-05-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_bsdsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAndAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('branch', models.CharField(choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong')], max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Upload image if media type is Photo', null=True, upload_to='events_achievements/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or other video URL if media type is Video', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event & Achievement',
                'verbose_name_plural': 'Events & Achievements',
                'ordering': ['-created_at'],
            },
        ),
    ]
