# Generated by Django 6.0.3 on 2026-04-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_top',
            field=models.BooleanField(default=False, help_text="Check to display this service on the homepage's top section"),
        ),
    ]
