# Generated by Django 6.0.3 on 2026-04-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='demo_description',
            field=models.TextField(blank=True, help_text='Information regarding service demos or examples', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features_description',
            field=models.TextField(blank=True, help_text='Details about the service features', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='introduction_description',
            field=models.TextField(blank=True, help_text='Introduction content for the service page', null=True),
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the FAQ appears')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='service.service')),
            ],
            options={
                'verbose_name': 'Service FAQ',
                'verbose_name_plural': 'Service FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the image appears in the gallery')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
