# Generated by Django 6.0.3 on 2026-04-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_demo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='short_name',
            field=models.CharField(blank=True, help_text='e.g., CADD (used for tabs and tight spaces)', max_length=50, null=True),
        ),
    ]
