# Generated by Django 6.0.3 on 2026-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicecategory_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload a small icon for this category (displayed in tab buttons)', null=True, upload_to='service/category_icons/'),
        ),
    ]
