# Generated by Django 6.0.3 on 2026-05-02 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_add_icon_to_servicecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(help_text='Short description for the home page card')),
                ('icon_svg', models.TextField(blank=True, help_text="Paste SVG code here for the icon. Make sure to use 'currentColor' for stroke/fill.", null=True)),
                ('icon_color', models.CharField(default='blue', help_text='Tailwind color name (e.g. blue, purple, cyan, teal, rose, amber)', max_length=50)),
                ('introduction_description', models.TextField(blank=True, null=True)),
                ('features_description', models.TextField(blank=True, null=True)),
                ('demo_description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='clinical_service/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Clinical Service',
                'verbose_name_plural': 'Clinical Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the FAQ appears')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='service.clinicalservice')),
            ],
            options={
                'verbose_name': 'Clinical Service FAQ',
                'verbose_name_plural': 'Clinical Service FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinical_service/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the image appears in the gallery')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service.clinicalservice')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
